name: Run Selenium Tests and Deploy Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install Maven dependencies
      run: mvn clean install -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Generate Allure Report
      run: mvn allure:report

    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Allure Report Artifact
      uses: actions/download-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
