name: Run Selenium Tests with Allure and Deploy Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install Maven dependencies
      run: mvn clean install -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Generate Allure Report
      run: |
        mvn io.qameta.allure:allure-maven:report
        mv target/site/allure-maven-plugin allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Allure Report artifact
      uses: actions/download-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
